version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Starting pre-build steps...

  build:
    commands:
      - echo Build started on `date`
      - python build_script.py

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'


